### ISSUE TITLE
No longer able to connect iOS app to server (affects iOS `14.8.x`)

### ISSUE THREAD

**Issue by Mack-Mack** [kungfoo/falcon-bms-control#19]
Firstly thank you for this excellent software.

I have been using it previously without issue. Having not played Falcon BMS for around a month I updated the iOS app on my iPad Pro 10.5 inch to 1.2.0, loaded the server (Version 0.4) and attempted to connect however no connection occurs. I am using Falcon BMS 4.35 Update 2 launched via the alternative launcher.

Server output:
Starting up...
Listening for broadcast packets on: 0.0.0.0:9020
Running on 0.0.0.0:9022

iPad:
Discovering server...

I have tried the following to rectify the issue:
Checked RTT is enabled in the BMS config
Deleted the server files and re installed
Checked the windows firewall settings (enabled for both public and private networks) I have no other firewalls or antivirus.
Launched the server as admin

Again thank you for this software, if you require and further info please ask.

**Comment by Mack-Mack** [comment]
Thanks for the reply Kungfoo.

I have checked the IP address's and they both share the same subnet (ie 192.168.0.XXX.) Interestingly I have a Surface tablet which is able to connect to the server using the PC client software included in the latest version. All the devices including the server connect to the router via Wifi. I have tried rebooting the router without success, any ideas what else to try? Thanks again for your time.

**Comment by kungfoo** [comment]
Okay, that sounds like an issue on the side of the iPad then. There is a new security popup that was introduced a while ago that shows the first time you launch the app, I think it says something like `Allow this app to discover devices on the network` IIRC.
You can find the setting in: Preferences > Privavy > Local Network > The app should be listed there. It says: "Apps that have requested permission to find and communicate with devices on your network will appear here."; And that toggle should be enabled. Otherwise I get the same behaviour as you.

**Comment by kungfoo** [comment]
It must be something either about this permission or the Wifi connection with the iPad. The network discovery code is exactly the same on the Windows release... Can you make triple sure, the iPad is on the same Wifi as the Surface (maybe 2.4Ghz vs. 5Ghz band)? My iPad sometimes connects to the wrong Wifi, just because it knows it's credentials, even though it has lower signal strength.

**Comment by turguthakki** [comment]
I'm having same issue with IOS 14.8.1. PC is at 192.168.1.5 and Tablet is 192.168.1.7 the application has right permissions. Android version works flawlessly.

**Comment by kungfoo** [comment]
Reading up on how Apple handles the new local network discovery permissions suggests, that this might actually be related to the iOS version you both have installed `14.8.x`. Is there any way for you to update to a newer iOS release? On my iPad running `15.0.2` it works. For it to work on 'legacy' devices, I first need to request the ﻿` com.apple.developer.networking.multicast` entitlement from apple and that is gonna take me a while.
I am not sure if this behavior is actually bugged in iOS 14, or if this is how it's supposed to work...

**Comment by Mack-Mack** [comment]
Thanks for the reply Kungfoo. Im holding back from updating to iPad OS 15 due to reports of bugs in the current version. I will test and report back once I do.

**Comment by kungfoo** [comment]
I have released a new version for iOS `1.3.0` that (once through review) enables you to manually enter the server ip address.
Other users have reported automatic discovery works for them once they upgrade to iOS `15.0.x` or `15.1` so you can pick the solution you favor.
