### ISSUE TITLE
MFD video signal stutters

### ISSUE THREAD

**Issue by mrcultureshock** [kungfoo/falcon-bms-control#22]
I just download the ios app of your application and everything connects fine. However, the MFD video signal stutters a bit. I changed the refresh rate but I don't see a change. Any tip on why this is happening?

Thank you!

**Comment by kungfoo** [comment]
Not sure what you mean by 'stutters'...

Here's how it works, maybe that clears things up a bit:

- BMS exports the texture for RTT at 1/2 the framerate of the sim by default. So if your BMS is only running at 60fps (VSync, or slow computer), then the exports are only updated at 30fps. No point in setting the refresh rate to 60fps in the app then, but also no harm done, since the server check of a frame is actually a new frame before sending it.
- At 30fps the video is not going to be butter smooth, but absolutely workable and better than any other solution I found that exports to tablets.
- If your Wifi network is slow: set the compression quality lower, say, around 60.
- If your device or your network is slow, set the refresh rate in the app to 30fps.

These last two points ensure that your network does not get congested and your device can actually receive _and_ display the frames as they arrive. If you go over the top with refresh rate and quality (the defaults are 30fps @ 80), the sustained data rate on your network is going to be higher and things can get congested.

I would say, this is not a bug. Please ensure your config matches your device and network. I've got the app running on a years old iPad Air, and it works quite flawlessly.

Let me know if that helps/clears things up a bit.

**Comment by mrcultureshock** [comment]
Hi Silvio,

I tried the app again and this time it was very smooth. Not sure what was going on the first time I used it. My connection is fast and haven't had Wifi problems. But you're right, the issue is on my end. I really enjoyed the app! Thanks for making it for the BMS community.
