### ISSUE TITLE
Server issue

### ISSUE THREAD

**Issue by maddog453** [kungfoo/falcon-bms-control#8]
I installed the server on my pc and start it then Falcon

I loaded Falcon control on my Ipad and run it.

I followed the instructions and changed the 0 to 1 per the instructions in the .cfg file in falcon.

The Ipad just keeps saying discovering server.

Help

Thanks

**Comment by kungfoo** [comment]
Did you get a prompt of windows firewall when you first started the server?
Please make sure that it's added to the list of applications that can open
ports on the network.

If that doesn't work:
Are the PC and IPad on the same network?

**Comment by maddog453** [comment]
I did get the prompt from Windows and allowed the program.

They are both on the same network. The PC uses both a T1 and wireless.

Is there anything else I need to do to Falcon besides change that enty in
the.cfg file from a 0 to a 1?

Thanks

Doug

**Comment by maddog453** [comment]
It appears that after a good night's sleep the computer has decided to play.

Actually I had both the ethernet and wireless on my PC. When I turned the
ethernet off it worked like a charm.
Looks really nice for those of us who are old and need vision help

Sorry for any inconvenience.

Doug

**Comment by kungfoo** [comment]
That's good to hear.

You can make it work using `wifi > ethernet` as well (I actually have that setup), but you need to make sure that the tablet on the wifi is on the same subnet as the ethernet, so both devices should have IP addresses like `192.168.1.x` where `x` is any number your router decides (static ot via dhcp). Depending on what router you have you may have to change the config to make that work. It is likely that your wifi and ethernet have different subnets by default and that it does not work because of that.

If none of this means anything to you, find a network savvy friend to set it up. :smile:

**Comment by maddog453** [comment]
Thanks for all your help

Doug
